### ISSUE TITLE
Pan-sharpening of HR Bands

### ISSUE THREAD

**Issue by melanievt** [lanha/SupReME#4]
Dear Charis,
I have one more inquiry. Although "sdf(d==1) = 0;" line isn't commented out in the "ms_fusion_apex.m" file, values of HR bands alter in the final product. I also tested the code by commenting out subject line, yet nothing much changed. Either way the code produces different values for HR bands. Could you please help out?
Best,
Mel

**Comment by lanha** [comment]
The values will change because all the bands (even the HR ones) will be a linear combination of the subspace "eigen"-images. Since our aim is not to sharpen the HR bands we only use them in the optimization cost to "inject" the HR info, and setting sdf=0 for those, means we assume there are as sharp as they should be. At the end of the day we don't care too much what the values of the HR bands are.

**Comment by melanievt** [comment]
Thank you for the explanation🙏
